- name: format
  task: prettier --write 'src/**/*.{js,css}'

- name: test/spec
  task: ava

- name: test/lint
  task: eslint "src/**/*.js"

- name: test
  tasks:
      - taskfile test/spec
      - - taskfile test/lint
      # - - - taskfile test/integration
