- name: format
  task: prettier --write '{src,bin}/**/*.{js,css}'

- name: test/spec
  task: ava

- name: test/lint
  task: eslint "{src,bin}/**/*.js"

- name: test/coverage
  tasks:
    - nyc ava
    - - nyc report --reporter=text-lcov | coveralls

- name: test
  tasks:
      - taskfile test/spec
      - - taskfile test/lint
