- name: format
  task: prettier --write '{src,bin}/**/*.js'

- name: test/spec
  task: ava

- name: test/lint
  tasks:
    - node -r @babel/register bin/index.js
    - - eslint "{src,bin}/**/*.js"

- name: test/coverage
  tasks:
    - nyc ava
    - - nyc report --reporter=text-lcov | coveralls

- name: test
  tasks:
    - taskfile test/spec
    - - taskfile test/lint

- name: prepublish
  tasks:
    - cp bin/index.js bin/index_backup.js
    - - rollup -c rollup.config.js

- name: postpublish
  task: mv bin/index_backup.js bin/index.js
